config/routes.rb
Rails.application.routes.draw do
  get 'minings/stop'
  get 'minings/restart'
  resources :minings

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#save'
  get 'settings/shutdown'
  get 'settings/reboot'

  root 'home#index'
end

app/models/mining.rb
# == Schema Information
#
# Table name: minings
#
#  id         :integer          not null, primary key
#  rig_id     :integer
#  code       :integer
#  miner      :integer
#  arg        :text
#  mining_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_minings_on_rig_id  (rig_id)
#

class Mining < ApplicationRecord
  enum miner: { ccminer: 0, claymore: 1, ethminer: 2, ewbf_miner: 3 }

  belongs_to :rig

  before_create :set_default_mining_at
  after_commit :start_mining

  def execute_cmd
    if code == 1
      miner_path = ''

      if self.miner == 'ccminer'
        miner_path = "cd #{Dir.pwd}/vendor/miners/ccminer && ./ccminer"
      elsif self.miner == 'claymore'
        miner_path = "cd #{Dir.pwd}/vendor/miners/claymore && ./ethdcrminer64"
      elsif self.miner == 'ethminer'
        miner_path = "cd #{Dir.pwd}/vendor/miners/ethminer/bin && ./ethminer"
      elsif self.miner == 'ewbf_miner'
        miner_path = "cd #{Dir.pwd}/vendor/miners/ewbf-miner && ./miner"
      end

      "#{miner_path} #{self.arg.gsub('$NAME', self.rig.name)}"
    else
      ''
    end
  end

  def set_default_mining_at
    self.mining_at = Time.zone.now if self.mining_at.blank?
  end

  def start_mining
    self.rig.start_mining
  end

  def to_s
    self.to_string
  end

  def to_string
    if code == 0
      'Stop Mining'
    else
      execute_cmd
    end
  end
end

app/controllers/minings_controller.rb
class MiningsController < ApplicationController
  before_action :set_mining, only: [:show, :edit, :update, :destroy]

  # GET /minings
  # GET /minings.json
  def index
    @page_title = Mining

    rig = Rig.default
    @mining = rig.minings.last

    rig.stop_mining if @mining.blank?

    @mining_logs = rig.mining_logs.order('id DESC').limit(1000)
  end

  # GET /minings/1
  # GET /minings/1.json
  def show
  end

  # GET /minings/new
  def new
    @page_title = 'Set mining'
    @mining = Mining.new rig: Rig.default, code: 1
  end

  # GET /minings/1/edit
  def edit
  end

  # POST /minings
  # POST /minings.json
  def create
    @mining = Mining.new(mining_params)

    respond_to do |format|
      if @mining.save
        format.html { redirect_to minings_path, notice: 'Mining has been set.' }
        format.json { render :show, status: :created, location: minings_path }
      else
        format.html { render :new }
        format.json { render json: @mining.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minings/1
  # PATCH/PUT /minings/1.json
  def update
    respond_to do |format|
      if @mining.update(mining_params)
        format.html { redirect_to @mining, notice: 'Mining has been set.' }
        format.json { render :show, status: :ok, location: @mining }
      else
        format.html { render :edit }
        format.json { render json: @mining.errors, status: :unprocessable_entity }
      end
    end
  end

  def stop
    rig = Rig.default
    rig.stop_mining

    flash[:notice] = 'Mining has been stop.'
    redirect_to minings_path
  end

  def restart
    rig = Rig.default
    rig.restart_miner

    flash[:notice] = 'Miner has been restart.'
    redirect_to minings_path
  end

  # DELETE /minings/1
  # DELETE /minings/1.json
  def destroy
    @mining.destroy
    respond_to do |format|
      format.html { redirect_to minings_url, notice: 'Mining was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining
      @mining = Mining.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_params
      params.require(:mining).permit(:rig_id, :code, :miner, :arg)
    end
end

app/helpers/minings_helper.rb
module MiningsHelper
end

app/views/minings/_form.html.haml
= simple_form_for(@mining) do |f|
  = f.error_notification

  .form-inputs
    = f.input :rig_id, as: :hidden
    = f.input :code, as: :hidden
    = f.input :miner
    = f.input :arg

  .form-actions
    = f.submit "Start Mining", class: 'btn btn-primary'

app/views/minings/edit.html.haml
%h1 Editing mining

= render 'form'

= link_to 'Show', @mining
\|
= link_to 'Back', minings_path

app/views/minings/index.html.haml
%h1 Mining
%p
  %strong Current mining command:
  = @mining.to_s
= link_to new_mining_path, class: 'btn btn-primary' do
  = icon 'fas', 'play'
  Set Mining
&nbsp;
= link_to minings_stop_path, class: 'btn btn-danger' do
  = icon 'fas', 'stop'
  Stop Mining
&nbsp;
= link_to minings_restart_path, class: 'btn btn-warning' do
  = icon 'fas', 'undo'
  Restart Miner
%hr/
%h1 Logs
%p
  %strong currently logs are not auto reload by themself. please, refresh this page manually for got new logs.
%p
  - @mining_logs.each do |mining_log|
    = mining_log.log_line
    %br/

app/views/minings/new.html.haml
%h1 Set mining

= render 'form'

= link_to 'Back', minings_path

%hr/
%h2 Help
%p You can look up for arguments from below list.
%ul
  %li
    CC Miner -
    = link_to 'https://github.com/tpruvot/ccminer/blob/windows/README.txt'
  %li
    Claymore -
    = link_to 'https://github.com/nanopool/Claymore-Dual-Miner'
  %li
    Ethminer -
    = link_to 'https://github.com/ethereum-mining/ethminer'
  %li
    Ewbf miner -
    = link_to 'Original from here', 'https://github.com/nanopool/ewbf-miner'
    but you can get help at
    = link_to 'https://github.com/nemosminer/EWBF-Zec-Miner/blob/master/Help.txt'
%h2 Example
%p
  Here is example of arg for each miner, and if you want to add worker name you can use
  %strong $NAME
  we will replace name of machine to worker name by automatically.
%ul
  %li
    CC Miner
    %ul
      %li
        = '-a neoscrypt -o stratum+tcp://asia1.gobyte.network:4233 -u GMPL211hSnzu3hsmVGZdDoVPcXbvTyAH5b.$NAME'
      %li
        = '-a lyra2v2 -o stratum+tcp://yiimp.gos.cx:4502 -u AJRPfBhmc9gSHev2P1oydKFFEc8uqZUzqw.$NAME - p c=ABS'
  %li
    Claymore
    %ul
      %li
        = '-epool eth-asia1.nanopool.org:9999 -ewal 0xbD66f2dbc698Faf1F8cFd95Dd5e136F9079860Aa/$NAME/pong@catmine.co -mode 1'
  %li
    Eth Miner
    %ul
      %li
        = '--farm-retries 200 -S eth-asia1.nanopool.org:9999 -O 0xbD66f2dbc698Faf1F8cFd95Dd5e136F9079860Aa.$NAME/pong@catmine.co -U -SP 1'
  %li
    Ewbf Miner
    %ul
      %li
        = '--server zec-asia1.nanopool.org --user t1Zy1BiKSRnzrwyoueWCB3ATwjg4fwNvWgk.$NAME/pong@catmine.co --pass z --port 6666'

app/views/minings/show.html.haml
%p#notice= notice

%p
  %b Rig:
  = @mining.rig
%p
  %b Code:
  = @mining.code
%p
  %b Args:
  = @mining.args

= link_to 'Edit', edit_mining_path(@mining)
\|
= link_to 'Back', minings_path