config/routes.rb
Rails.application.routes.draw do
  get 'minings/stop'
  get 'minings/restart'
  resources :minings

  get 'settings', to: 'settings#index'
  patch 'settings', to: 'settings#save'
  get 'settings/shutdown'
  get 'settings/reboot'

  root 'home#index'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @page_title = 'Settings'
    @rig = Rig.default
  end

  def save
    @rig = Rig.default
    if @rig.update(rig_params)
      flash[:notice] = 'Your settings have been saved.'
    else
      flash[:alert] = 'Error!'
    end

    render 'index'
  end

  def shutdown
    @rig = Rig.default
    machine = CatminerClient::Machine.new @rig
    machine.shutdown
  end

  def reboot
    @rig = Rig.default
    machine = CatminerClient::Machine.new @rig
    machine.reboot
  end

  private
    def rig_params
      params.require(:rig).permit :name, gpus_attributes: [:id, :power_limit, :mem_clock, :gpu_clock]
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.haml
%h1 Settings
= simple_form_for @rig, url: settings_path do |f|
  = f.input :name
  %h2 Overclock
  %table.table.table-responsive.table-striped
    %thead
      %tr
        %th{ scope: 'col' } No
        %th{ scope: 'col' } GPU
        %th{ scope: 'col' } Power limit (W)
        %th{ scope: 'col' } Memory overclock (Hz)
        %th{ scope: 'col' } GPU overclock (Hz)
    %tbody
      - i = 1
      = f.simple_fields_for(:gpus) do |gpu_f|
        %tr
          %td= i
          %td
            = gpu_f.object.name
            = gpu_f.input :id, as: :hidden
          %td= gpu_f.input :power_limit, label: false
          %td= gpu_f.input :gpu_clock, label: false
          %td= gpu_f.input :mem_clock, label: false
        - i += 1
  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
%hr/
%h1 Command
= link_to settings_reboot_path, class: 'btn btn-warning' do
  = icon 'fas', 'undo'
  Reboot
&nbsp;
= link_to settings_shutdown_path, class: 'btn btn-danger' do
  = icon 'fas', 'stop'
  Shutdown